name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file with Firebase config
        run: |
          echo "VITE_FIREBASE_APIKEY=${{ secrets.APIKEY }}" >> .env
          echo "VITE_FIREBASE_APPID=${{ secrets.APPID }}" >> .env
          echo "VITE_FIREBASE_AUTHDOMAIN=${{ secrets.AUTHDOMAIN }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENTID=${{ secrets.MEASUREMENTID }}" >> .env
          echo "VITE_FIREBASE_MESSAGINGSENDERID=${{ secrets.MESSAGINGSENDERID }}" >> .env
          echo "VITE_FIREBASE_PROJECTID=${{ secrets.PROJECTID }}" >> .env
          echo "VITE_FIREBASE_STORAGEBUCKET=${{ secrets.STORAGEBUCKET }}" >> .env

      - name: Install dependencies
        run: |
          npm install
          npm install firebase  

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
